sonar.projectKey=pii-guard
sonar.projectName=Модуль безопасности персональных данных
sonar.sources=.
sonar.exclusions=**/*_test.go,docs/**,deploy/**,tools/**,scripts/**,testdata/**,**/testdata/**,tasks/**,corpus/**,dist/**,bin/**,*.md
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.json
sonar.go.golangci-lint.reportPaths=golangci-report.xml
sonar.go.govet.reportPaths=govet-report.out
sonar.coverage.exclusions=cmd/gen/**,cmd/corpus/**
sonar.sourceEncoding=UTF-8